openapi: 3.0.3
info:
  title: URL Shortener API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/links:
    post:
      summary: Crear short link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url: { type: string, format: uri }
                expiresAt: { type: string, format: date-time }
              required: [url]
      responses:
        '201': { description: Created }
  /{code}:
    get:
      summary: Redirige y registra click
      parameters:
        - in: path
          name: code
          required: true
          schema: { type: string }
      responses:
        '302': { description: Redirect }